version: '3.8'

volumes:
  postgres-data:


services:
  postgresql:
    container_name: postgresql
    image: postgres:15.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file: .env.local
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresql