"""User

Revision ID: ae41e887af75
Revises: 
Create Date: 2023-08-02 23:33:05.820603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae41e887af75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA user')
    op.create_table('task',
    sa.Column('name', sa.String(), nullable=False, comment='name of user'),
    sa.Column('email', sa.String(), nullable=False, comment='email'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='passwd'),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    schema='user',
    comment='Table with all tasks'
    )
    op.create_index(op.f('ix_user_task_email'), 'task', ['email'], unique=True, schema='user')
    op.create_index(op.f('ix_user_task_name'), 'task', ['name'], unique=False, schema='user')
    op.create_index(op.f('ix_user_task_sid'), 'task', ['sid'], unique=True, schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_task_sid'), table_name='task', schema='user')
    op.drop_index(op.f('ix_user_task_name'), table_name='task', schema='user')
    op.drop_index(op.f('ix_user_task_email'), table_name='task', schema='user')
    op.drop_table('task', schema='user')
    op.execute('DROP SCHEMA user')
    # ### end Alembic commands ###
